(()=>{"use strict";const root=document.documentElement,VAR="cug-darkgpt-vars",AMBIENT="cug-darkgpt-ambient";let settings=CUG.normalize(null),fx=null,failed=false,textFx=null;
function vars(){let e=document.getElementById(VAR);if(!e){e=document.createElement("style");e.id=VAR;(document.head||root).appendChild(e)}e.textContent=`html[data-cug-darkgpt]{--cug-set-alpha:${(settings.panelBrightness/100).toFixed(2)};--cug-set-veil:${(settings.backgroundBrightness/100).toFixed(2)};--cug-set-sat:135%;--cug-set-shine:.65;--cug-set-radius:18px;--cug-set-glow-radius:${settings.glowRadius}px;--cug-set-accent:239 38 58;}`}
function ambient(){let e=document.getElementById(AMBIENT);if(!e){e=document.createElement("div");e.id=AMBIENT;e.innerHTML="<canvas></canvas><i></i><i></i><i></i>";e.setAttribute("aria-hidden","true");root.appendChild(e)}return e}
function sync(){const c=ambient().querySelector("canvas");if(!settings.enabled||failed){fx?.destroy();fx=null;root.setAttribute("data-cug-fx","css");return}if(!fx){fx=CUGFX.create(c);if(!fx){failed=true;root.setAttribute("data-cug-fx","css");return}fx.start()}fx.update(CUGFX.paramsFrom(settings,false));root.setAttribute("data-cug-fx","gl")}
function findHeadline(){return [...document.querySelectorAll("h1")].find(h=>h.textContent.trim()==="Ready when you are.")?.querySelector("div.px-1")||[...document.querySelectorAll("h1")].find(h=>h.textContent.trim()==="Ready when you are.")?.firstElementChild}
function startParticles(){if(textFx||!settings.enabled)return;const target=findHeadline();if(!target){setTimeout(startParticles,500);return;}const canvas=document.createElement("canvas");canvas.id="cug-darkgpt-particle-text";canvas.setAttribute("aria-hidden","true");canvas.style.cssText="position:fixed;pointer-events:none;z-index:30;left:0;top:0;";document.documentElement.appendChild(canvas);textFx={target,canvas,points:[],mouse:{x:-9999,y:-9999},raf:0};target.setAttribute("data-cug-particle-source","true");target.style.color="transparent";target.style.webkitTextFillColor="transparent";rebuildParticles();window.addEventListener("pointermove",onMouse,{passive:true});window.addEventListener("resize",rebuildParticles,{passive:true});textFx.raf=requestAnimationFrame(particleFrame)}
function rebuildParticles(){if(!textFx)return;const r=textFx.target.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.max(1,Math.ceil(r.width)),h=Math.max(1,Math.ceil(r.height));const c=textFx.canvas;c.width=w*d;c.height=h*d;c.style.width=w+"px";c.style.height=h+"px";c.style.left=r.left+"px";c.style.top=r.top+"px";const o=document.createElement("canvas"),x=o.getContext("2d");o.width=w*d;o.height=h*d;x.scale(d,d);const st=getComputedStyle(textFx.target);x.font=st.font;x.textBaseline="middle";x.fillStyle="#fff";x.fillText("Ready when you are.",0,h/2);const data=x.getImageData(0,0,w*d,h*d).data,step=Math.max(2,Math.round(3/d)),pts=[];for(let y=0;y<h*d;y+=step)for(let xx=0;xx<w*d;xx+=step)if(data[(y*w*d+xx)*4+3]>120)pts.push({x:xx/d,y:y/d,ox:xx/d,oy:y/d,vx:0,vy:0,s:.65+Math.random()*.7});textFx.points=pts}
function onMouse(e){if(textFx)textFx.mouse={x:e.clientX,y:e.clientY};root.style.setProperty("--cug-mx",e.clientX+"px");root.style.setProperty("--cug-my",e.clientY+"px")}
function particleFrame(){if(!textFx)return;const r=textFx.target.getBoundingClientRect(),c=textFx.canvas,d=Math.min(2,devicePixelRatio||1),x=c.getContext("2d"),m=textFx.mouse;x.clearRect(0,0,c.width,c.height);for(const p of textFx.points){const dx=p.x-(m.x-r.left),dy=p.y-(m.y-r.top),dist=Math.hypot(dx,dy)||1,f=Math.max(0,1-dist/110);p.vx+=(dx/dist)*f*7*.035+(p.ox-p.x)*.045;p.vy+=(dy/dist)*f*7*.035+(p.oy-p.y)*.045;p.vx*=.88;p.vy*=.88;p.x+=p.vx;p.y+=p.vy;x.beginPath();x.arc(p.x*d,p.y*d,p.s*d,0,Math.PI*2);x.fillStyle="rgb(255 "+(70+Math.round(f*90))+" "+(82+Math.round(f*60))+")";x.shadowBlur=f*9*d;x.shadowColor="rgba(239,38,58,.9)";x.fill()}textFx.raf=requestAnimationFrame(particleFrame)}
function stopParticles(){if(!textFx)return;cancelAnimationFrame(textFx.raf);window.removeEventListener("pointermove",onMouse);window.removeEventListener("resize",rebuildParticles);textFx.target.style.removeProperty("color");textFx.target.style.removeProperty("-webkit-text-fill-color");textFx.canvas.remove();textFx=null}
function apply(s){settings=s;if(!s.enabled){["data-cug-darkgpt","data-cug-mode","data-cug-hover3d","data-cug-motion","data-cug-drag","data-cug-fx"].forEach(n=>root.removeAttribute(n));fx?.destroy();fx=null;stopParticles();document.getElementById(VAR)?.remove();document.getElementById(AMBIENT)?.remove();return}vars();root.setAttribute("data-cug-darkgpt","true");root.setAttribute("data-cug-mode","dark");root.setAttribute("data-cug-hover3d","on");root.setAttribute("data-cug-motion","on");root.setAttribute("data-cug-drag","on");sync();requestAnimationFrame(startParticles)}
chrome.storage.onChanged.addListener((c,a)=>{if(a==="local"&&c[CUG.STORAGE_KEY])apply(CUG.normalize(c[CUG.STORAGE_KEY].newValue))});CUG.load().then(apply).catch(()=>{});
})();